import test from 'node:test'
import assert from 'node:assert/strict'
import { isWebsiteReport } from '../src/website-report.js'
const unavailable = () => ({ fetchedAt: '2026-10-04T12:00:00Z', ga4: { status: 'unavailable', detail: 'Unavailable' }, gsc: { status: 'unavailable', detail: 'Unavailable' } })
const healthy = () => ({ ...unavailable(), ga4: { status: 'ok', detail: 'Ready', window: { startDate: '2026-09-01', endDate: '2026-09-28', timeZone: 'America/Los_Angeles' }, totals: { users: 10, sessions: 20, pageViews: 30, engagementRate: 0.5 }, pages: [{ path: '/', views: 20 }], quality: { thresholded: false, sampled: false, otherRow: false } }, gsc: { status: 'ok', detail: 'Ready', window: { startDate: '2026-08-30', endDate: '2026-09-26', timeZone: 'America/Los_Angeles' }, totals: { clicks: 5, impressions: 100, ctr: 0.05, position: 7.2 }, queries: [{ query: 'dentist', clicks: 4, impressions: 40, ctr: 0.1, position: 3 }] } })
test('website validator accepts unavailable and independent healthy reporting windows', () => { assert.equal(isWebsiteReport(unavailable()), true); assert.equal(isWebsiteReport(healthy()), true) })
test('website validator rejects missing totals and malformed nested table values', () => { const value = healthy(); delete value.ga4.totals; assert.equal(isWebsiteReport(value), false); const broken = healthy(); broken.gsc.queries[0].position = '7'; assert.equal(isWebsiteReport(broken), false); const rows = healthy(); rows.ga4.pages = [null]; assert.equal(isWebsiteReport(rows), false) })
test('website validator rejects invalid dates, rates, and non-finite counts', () => { for (const change of [value => { value.ga4.window.startDate = '2026-02-30' }, value => { value.gsc.window.endDate = '2020-01-01' }, value => { value.ga4.totals.engagementRate = 5 }, value => { value.ga4.totals.users = NaN }, value => { value.ga4.latestDate = 'invalid' }, value => { value.ga4.quality.sampled = 'false' }]) { const value = healthy(); change(value); assert.equal(isWebsiteReport(value), false) } })
test('website validator rejects null, arrays, invalid sources and non-object bodies', () => { for (const value of [null, [], true, 'ok', {}, { ...unavailable(), ga4: null }, { ...unavailable(), fetchedAt: 'invalid' }]) assert.equal(isWebsiteReport(value), false) })
