import { useState, type ReactNode } from 'react'
import { Activity, ArrowUpRight, ChartNoAxesCombined, CircleHelp, Eye, Globe2, MousePointer2, Search, Users, type LucideIcon } from 'lucide-react'
import { Button } from './ui/button'
import { Badge } from './ui/badge'
import { Card, CardContent, CardHeader, CardTitle } from './ui/card'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from './ui/dialog'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from './ui/table'
import { ToggleGroup, ToggleGroupItem } from './ui/toggle-group'
import { Skeleton } from './ui/skeleton'

type SourceStatus = 'ok' | 'unavailable' | 'synthetic'
type ReportingWindow = { startDate: string; endDate: string; timeZone: string }
type SearchMetrics = { clicks: number; impressions: number; ctr: number; position: number }
export type WebsiteReport = {
  fetchedAt: string
  ga4: { status: SourceStatus; detail: string; propertyId?: string; window?: ReportingWindow; latestDate?: string | null; totals?: { users: number; sessions: number; pageViews: number; engagementRate: number }; channels?: { name: string; sessions: number }[]; pages?: { path: string; views: number }[]; events?: { name: string; count: number }[]; quality?: { thresholded: boolean; sampled: boolean; otherRow: boolean } }
  gsc: { status: SourceStatus; detail: string; siteUrl?: string; window?: ReportingWindow; latestDate?: string | null; totals?: SearchMetrics; queries?: (SearchMetrics & { query: string })[]; pages?: (SearchMetrics & { page: string })[] }
}
const number = (value?: number) => typeof value === 'number' && Number.isFinite(value) ? new Intl.NumberFormat('en-US').format(value) : '—'
const percent = (value?: number) => typeof value === 'number' && Number.isFinite(value) ? new Intl.NumberFormat('en-US', { style: 'percent', maximumFractionDigits: 1 }).format(value) : '—'
const date = (value: string) => /^\d{4}-\d{2}-\d{2}$/.test(value) && Number.isFinite(Date.parse(`${value}T12:00:00Z`)) ? new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC' }).format(new Date(`${value}T12:00:00Z`)) : value
const windowLabel = (window?: ReportingWindow) => window ? `${date(window.startDate)} – ${date(window.endDate)}` : 'Reporting dates unavailable'
const ready = (source?: { status: SourceStatus }) => source?.status === 'ok' || source?.status === 'synthetic'
function Info({ title, children }: { title: string; children: ReactNode }) {
  return <Dialog><DialogTrigger render={<Button variant="ghost" size="icon-sm" className="shrink-0 text-muted-foreground" aria-label={`About ${title}`} />}><CircleHelp aria-hidden="true" /></DialogTrigger><DialogContent className="max-h-[85svh] overflow-y-auto p-6 sm:max-w-lg"><DialogHeader className="pr-6"><DialogTitle>{title}</DialogTitle><DialogDescription>Sources and measurement</DialogDescription></DialogHeader><div className="flex flex-col gap-4 text-sm leading-relaxed text-muted-foreground">{children}</div></DialogContent></Dialog>
}
function Metric({ label, value, icon: Icon, loading, source, window, children }: { label: string; value: string; icon: LucideIcon; loading: boolean; source: string; window?: ReportingWindow; children: ReactNode }) {
  return <Card className="gap-8 rounded-2xl p-6 shadow-none ring-foreground/6 sm:p-7"><CardHeader className="flex flex-row items-center justify-between p-0"><span className="flex size-10 items-center justify-center rounded-xl bg-muted/60 text-primary"><Icon className="size-5" strokeWidth={1.6} aria-hidden="true" /></span><Info title={label}>{children}</Info></CardHeader><CardContent className="flex flex-col gap-2 p-0"><p className="text-sm text-muted-foreground">{label}</p>{loading ? <Skeleton className="h-10 w-28" /> : <p className="text-3xl font-medium tracking-tight tabular-nums sm:text-4xl">{value}</p>}{value === '—' && !loading && <p className="text-xs text-muted-foreground">Unavailable</p>}<p className="mt-3 text-xs leading-relaxed text-muted-foreground">{source}<span className="block">{windowLabel(window)}</span></p></CardContent></Card>
}
function DataTable({ title, heading, rows, valueLabel }: { title: string; heading: string; rows: { name: string; value: number }[]; valueLabel: string }) {
  return <Card className="min-w-0 rounded-2xl py-6 [--card-spacing:--spacing(6)] sm:py-8 sm:[--card-spacing:--spacing(8)]"><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="min-w-0">{rows.length ? <Table className="min-w-0"><TableHeader><TableRow><TableHead>{heading}</TableHead><TableHead className="text-right">{valueLabel}</TableHead></TableRow></TableHeader><TableBody>{rows.map((row, index) => <TableRow key={`${row.name}-${index}`} className="[&>td]:py-5"><TableCell className="max-w-64 whitespace-normal break-words">{row.name || '(not set)'}</TableCell><TableCell className="text-right tabular-nums">{number(row.value)}</TableCell></TableRow>)}</TableBody></Table> : <p className="py-8 text-sm text-muted-foreground">No rows reported in this window.</p>}</CardContent></Card>
}
export function WebsiteData({ report, loading, view }: { report: WebsiteReport | null; loading: boolean; view: 'overview' | 'activity' }) {
  const [tab, setTab] = useState('traffic')
  const [searchTab, setSearchTab] = useState('queries')
  const ga = report?.ga4
  const gsc = report?.gsc
  const gaReady = ready(ga) && Boolean(ga?.totals)
  const gscReady = ready(gsc) && Boolean(gsc?.totals)
  const busy = loading && !report
  const quality = ga?.quality
  const freshness = <p>Checked {report?.fetchedAt && Number.isFinite(Date.parse(report.fetchedAt)) ? new Date(report.fetchedAt).toLocaleString('en-US', { timeZone: 'America/Los_Angeles', timeZoneName: 'short' }) : 'time unavailable'}. Successful reports may be reused for up to 15 minutes.</p>
  const gaDetails = <>{freshness}<p>GA4 active users are measured visitors, not patients. Sessions and page views describe website usage and may be affected by consent choices.</p><p>{windowLabel(ga?.window)}. Reporting timezone: {ga?.window?.timeZone || 'Unavailable'}. Recent GA4 data may still be processing.</p><p>Engagement rate is the share of sessions GA4 classifies as engaged. Interaction events do not confirm appointments, calls, or leads.</p>{ga?.latestDate && <p>Latest observed activity: {date(ga.latestDate)}.</p>}{ga && !gaReady && <p>{ga.detail}</p>}{quality?.thresholded && <p>Privacy thresholds were applied; some data may be withheld.</p>}{quality?.sampled && <p>This report contains sampled data.</p>}{quality?.otherRow && <p>Some high-cardinality values were grouped into an “other” row.</p>}{ga?.status === 'synthetic' && <p>Synthetic demonstration data.</p>}</>
  const searchDetails = <>{freshness}<p>Google Search Console measures this site's visibility in Google Search. Clicks are search-result clicks, not booked appointments.</p><p>{windowLabel(gsc?.window)}. Reporting timezone: {gsc?.window?.timeZone || 'Unavailable'}. Only final data is requested.</p>{gsc?.latestDate && <p>Latest observed search date: {date(gsc.latestDate)}. This is the latest date returned, not a guarantee of reporting freshness.</p>}<p>Average position is impression-weighted. Query anonymization and reporting limits mean the top rows do not add up to the totals above.</p>{gsc && !gscReady && <p>{gsc.detail}</p>}{gsc?.status === 'synthetic' && <p>Synthetic demonstration data.</p>}</>
  const metric = (label: string, value: string, icon: LucideIcon, source: 'GA4' | 'Search Console') => <Metric key={label} label={label} value={value} icon={icon} loading={busy} source={source} window={source === 'GA4' ? ga?.window : gsc?.window}>{source === 'GA4' ? gaDetails : searchDetails}</Metric>
  const gaValue = (key: 'users' | 'sessions' | 'pageViews') => gaReady ? number(ga?.totals?.[key]) : '—'
  const searchValue = (key: 'clicks' | 'impressions') => gscReady ? number(gsc?.totals?.[key]) : '—'
  const source = tab === 'traffic' ? ga : gsc
  const sourceReady = tab === 'traffic' ? gaReady : gscReady
  const searchRows = searchTab === 'queries' ? (gsc?.queries || []).map(row => ({ ...row, name: row.query })) : (gsc?.pages || []).map(row => ({ ...row, name: row.page }))
  const events = [{ name: 'schedule_click', label: 'Scheduling clicks' }, { name: 'contact_click', label: 'Contact actions' }, { name: 'cta_click', label: 'Other CTA clicks' }].flatMap(event => { const row = ga?.events?.find(item => item.name === event.name); return row ? [{ name: event.label, value: row.count }] : [] })
  return <section className="flex min-w-0 flex-col gap-8" aria-label="Website and search reporting">
    {view === 'overview' && quality && (quality.thresholded || quality.sampled || quality.otherRow) && <div className="flex flex-wrap items-center gap-2 text-xs text-muted-foreground" role="status"><span>GA4</span>{quality.thresholded && <Badge variant="outline">Privacy-limited</Badge>}{quality.sampled && <Badge variant="outline">Sampled</Badge>}{quality.otherRow && <Badge variant="outline">Grouped data</Badge>}</div>}
    {view === 'overview' ? <div className="grid gap-5 sm:grid-cols-2">{metric('Website users', gaValue('users'), Users, 'GA4')}{metric('Search clicks', searchValue('clicks'), Search, 'Search Console')}</div> : <>
      <div className="flex flex-wrap items-center justify-between gap-4"><ToggleGroup variant="outline" aria-label="Website data source" value={[tab]} onValueChange={values => { if (values[0]) setTab(values[0]) }}><ToggleGroupItem value="traffic"><Globe2 aria-hidden="true" />Traffic</ToggleGroupItem><ToggleGroupItem value="search"><Search aria-hidden="true" />Search</ToggleGroupItem></ToggleGroup><div className="flex items-center gap-2"><span className="text-xs text-muted-foreground">{tab === 'traffic' ? 'GA4' : 'Search Console'}</span><Info title={tab === 'traffic' ? 'Website traffic' : 'Search performance'}>{tab === 'traffic' ? gaDetails : searchDetails}</Info></div></div>
      {tab === 'traffic' && quality && (quality.thresholded || quality.sampled || quality.otherRow) && <div className="flex flex-wrap gap-2" role="status">{quality.thresholded && <Badge variant="outline">Privacy-limited</Badge>}{quality.sampled && <Badge variant="outline">Sampled</Badge>}{quality.otherRow && <Badge variant="outline">Grouped data</Badge>}</div>}
      <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{tab === 'traffic' ? <>{metric('Active users', gaValue('users'), Users, 'GA4')}{metric('Sessions', gaValue('sessions'), Activity, 'GA4')}{metric('Page views', gaValue('pageViews'), Eye, 'GA4')}{metric('Engagement rate', gaReady ? percent(ga?.totals?.engagementRate) : '—', ChartNoAxesCombined, 'GA4')}</> : <>{metric('Search clicks', searchValue('clicks'), MousePointer2, 'Search Console')}{metric('Impressions', searchValue('impressions'), Eye, 'Search Console')}{metric('Click-through rate', gscReady ? percent(gsc?.totals?.ctr) : '—', ArrowUpRight, 'Search Console')}{metric('Average position', gscReady && gsc?.totals ? gsc.totals.position.toFixed(1) : '—', ChartNoAxesCombined, 'Search Console')}</>}</div>
      {busy ? <Skeleton className="h-56 w-full rounded-2xl" /> : !sourceReady ? <Card className="rounded-2xl p-8"><CardHeader className="p-0"><CardTitle>{tab === 'traffic' ? 'Traffic data unavailable' : 'Search data unavailable'}</CardTitle></CardHeader><CardContent className="p-0 text-sm leading-relaxed text-muted-foreground">{source?.detail || 'This source could not be refreshed. Use Refresh to try again.'}</CardContent></Card> : tab === 'traffic' ? <><div className="grid min-w-0 gap-6 lg:grid-cols-2"><DataTable title="Top channels" heading="Channel" valueLabel="Sessions" rows={(ga?.channels || []).map(row => ({ name: row.name, value: row.sessions }))} /><DataTable title="Top pages" heading="Page" valueLabel="Views" rows={(ga?.pages || []).map(row => ({ name: row.path, value: row.views }))} /></div><DataTable title="Website interactions" heading="Action" valueLabel="Events" rows={events} /></> : <Card className="min-w-0 rounded-2xl py-6 [--card-spacing:--spacing(6)] sm:py-8 sm:[--card-spacing:--spacing(8)]"><CardHeader className="flex flex-wrap items-center justify-between gap-4"><CardTitle>Search discovery</CardTitle><ToggleGroup variant="outline" aria-label="Search breakdown" value={[searchTab]} onValueChange={values => { if (values[0]) setSearchTab(values[0]) }}><ToggleGroupItem value="queries">Queries</ToggleGroupItem><ToggleGroupItem value="pages">Pages</ToggleGroupItem></ToggleGroup></CardHeader><CardContent className="min-w-0">{searchRows.length ? <Table className="min-w-0"><TableHeader><TableRow><TableHead>{searchTab === 'queries' ? 'Query' : 'Page'}</TableHead><TableHead className="text-right">Clicks</TableHead><TableHead className="text-right">Impressions</TableHead><TableHead className="text-right">CTR</TableHead><TableHead className="text-right">Position</TableHead></TableRow></TableHeader><TableBody>{searchRows.map((row, index) => <TableRow key={`${row.name}-${index}`} className="[&>td]:py-5"><TableCell className="min-w-40 max-w-80 whitespace-normal break-words">{row.name}</TableCell><TableCell className="text-right tabular-nums">{number(row.clicks)}</TableCell><TableCell className="text-right tabular-nums">{number(row.impressions)}</TableCell><TableCell className="text-right tabular-nums">{percent(row.ctr)}</TableCell><TableCell className="text-right tabular-nums">{row.position.toFixed(1)}</TableCell></TableRow>)}</TableBody></Table> : <p className="py-8 text-sm text-muted-foreground">No search rows reported in this window.</p>}</CardContent></Card>}
    </>}
  </section>
}
